import { useState } from 'react'
import DemoShell, { Section, CodeBlock, SimButton, ResultPanel } from '../components/DemoShell'

const SOURCE = `// src/utils/validatePassword.js
export function validatePassword(password) {
  const errors = [];
  
  if (!password) {
    return { valid: false, errors: ['Password is required'] };
  }
  if (password.length < 8) {
    errors.push('Must be at least 8 characters');
  }
  if (password.length > 128) {
    errors.push('Must be 128 characters or less');
  }
  if (!/[A-Z]/.test(password)) {
    errors.push('Must contain an uppercase letter');
  }
  if (!/[0-9]/.test(password)) {
    errors.push('Must contain a number');
  }
  if (!/[!@#$%^&*]/.test(password)) {
    errors.push('Must contain a special character');
  }
  
  return { valid: errors.length === 0, errors };
}`

const GENERATED_TESTS = `// Generated by AI — 14 test cases covering all branches

import { validatePassword } from './validatePassword';

describe('validatePassword', () => {
  // Happy path
  test('accepts a valid password', () => {
    const result = validatePassword('MyPass1!');
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  // Null/empty cases
  test('rejects null password', () => {
    const result = validatePassword(null);
    expect(result.valid).toBe(false);
    expect(result.errors).toContain('Password is required');
  });

  test('rejects undefined password', () => {
    const result = validatePassword(undefined);
    expect(result.valid).toBe(false);
  });

  test('rejects empty string', () => {
    const result = validatePassword('');
    expect(result.valid).toBe(false);
  });

  // Length boundaries
  test('rejects 7-char password (below minimum)', () => {
    const result = validatePassword('Abc1!xx');
    expect(result.errors).toContain('Must be at least 8 characters');
  });

  test('accepts 8-char password (exact minimum)', () => {
    const result = validatePassword('Abcde1!x');
    expect(result.valid).toBe(true);
  });

  test('accepts 128-char password (exact maximum)', () => {
    const pw = 'A1!' + 'a'.repeat(125);
    const result = validatePassword(pw);
    expect(result.valid).toBe(true);
  });

  test('rejects 129-char password (over maximum)', () => {
    const pw = 'A1!' + 'a'.repeat(126);
    const result = validatePassword(pw);
    expect(result.errors).toContain('Must be 128 characters or less');
  });

  // Missing character types
  test('rejects password without uppercase', () => {
    const result = validatePassword('mypass1!');
    expect(result.errors).toContain('Must contain an uppercase letter');
  });

  test('rejects password without number', () => {
    const result = validatePassword('MyPasss!');
    expect(result.errors).toContain('Must contain a number');
  });

  test('rejects password without special char', () => {
    const result = validatePassword('MyPass12');
    expect(result.errors).toContain('Must contain a special character');
  });

  // Multiple errors
  test('returns all applicable errors at once', () => {
    const result = validatePassword('short');
    expect(result.valid).toBe(false);
    expect(result.errors.length).toBeGreaterThanOrEqual(3);
  });

  // Edge cases
  test('handles password with only special chars', () => {
    const result = validatePassword('!@#$%^&*!@#$%^&*');
    expect(result.errors).toContain('Must contain an uppercase letter');
    expect(result.errors).toContain('Must contain a number');
  });

  test('accepts password with all valid special chars', () => {
    const result = validatePassword('Test1!@#$%^&*');
    expect(result.valid).toBe(true);
  });
});`

const COVERAGE = [
  { line: 'password === null/undefined', covered: true },
  { line: 'password === empty string', covered: true },
  { line: 'length < 8', covered: true },
  { line: 'length === 8 (boundary)', covered: true },
  { line: 'length > 128', covered: true },
  { line: 'length === 128 (boundary)', covered: true },
  { line: 'missing uppercase', covered: true },
  { line: 'missing number', covered: true },
  { line: 'missing special char', covered: true },
  { line: 'multiple errors combined', covered: true },
  { line: 'all rules pass', covered: true },
]

export default function TestGeneration() {
  const [step, setStep] = useState(0)
  const [running, setRunning] = useState(false)

  const simulate = () => {
    setRunning(true)
    setTimeout(() => { setStep(1); setRunning(false) }, 2000)
  }

  return (
    <DemoShell useCase={4} icon="🧪" title="AI Test Case Generation"
      description="Paste your source code and AI generates comprehensive tests — including edge cases, boundary values, and error scenarios that humans typically miss."
      stats={[
        { value: '50%', label: 'Faster Creation (Microsoft)' },
        { value: '35%', label: 'More Coverage' },
        { value: '14', label: 'Tests Generated' },
        { value: '100%', label: 'Branch Coverage' },
      ]}>

      <Section title="1. Source Code">
        <CodeBlock title="validatePassword.js — your code" code={SOURCE} />
      </Section>

      <Section title="2. Generate Tests">
        <SimButton onClick={simulate} running={running}>🧪 Generate Test Suite</SimButton>
      </Section>

      <ResultPanel show={step >= 1} title="Generated Tests (14 test cases)">
        <CodeBlock code={GENERATED_TESTS} />

        <div style={{ marginTop: '1rem' }}>
          <div style={{ fontWeight: 600, fontSize: '0.85rem', marginBottom: '0.5rem' }}>Branch Coverage Analysis</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
            {COVERAGE.map((c, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.8rem' }}>
                <span>{c.covered ? '✅' : '❌'}</span>
                <span style={{ color: c.covered ? '#555' : '#c62828' }}>{c.line}</span>
              </div>
            ))}
          </div>
        </div>
      </ResultPanel>
    </DemoShell>
  )
}
